export default {
  name: "event",
  title: "Veranstaltung",
  type: "document",
  fields: [
    { name: "title", title: "Titel", type: "string", validation: (Rule: any) => Rule.required() },
    { name: "slug", title: "Slug", type: "slug", options: { source: "title", maxLength: 96 }, validation: (Rule: any) => Rule.required() },
    { name: "published", title: "Veröffentlicht", type: "boolean", initialValue: false },
    { name: "startDate", title: "Beginn", type: "datetime", validation: (Rule: any) => Rule.required() },
    { name: "endDate", title: "Ende", type: "datetime" },
    { name: "weekday", title: "Wochentag", type: "string" },
    { name: "time", title: "Anzeigezeit", type: "string" },
    { name: "duration", title: "Dauer", type: "string" },
    { name: "location", title: "Ort", type: "string" },
    { name: "address", title: "Adresse", type: "string" },
    { name: "summary", title: "Kurzbeschreibung", type: "text", rows: 3 },
    { name: "body", title: "Beschreibung", type: "array", of: [{ type: "block" }] },
    { name: "registrationUrl", title: "Anmeldelink", type: "url" },
    { name: "flyer", title: "Flyer", type: "file", options: { storeOriginalFilename: true } },
    {
      name: "gallery",
      title: "Galerie",
      type: "array",
      of: [{ type: "image", options: { hotspot: true }, fields: [{ name: "alt", title: "Alternativtext", type: "string", validation: (Rule: any) => Rule.required() }, { name: "caption", title: "Bildunterschrift", type: "string" }] }],
    },
    {
      name: "partners",
      title: "Partner",
      type: "array",
      of: [{ type: "object", fields: [{ name: "name", title: "Name", type: "string", validation: (Rule: any) => Rule.required() }, { name: "url", title: "Website", type: "url" }, { name: "logo", title: "Logo", type: "image" }] }],
    },
    {
      name: "funders",
      title: "Förderer",
      type: "array",
      of: [{ type: "object", fields: [{ name: "name", title: "Name", type: "string", validation: (Rule: any) => Rule.required() }, { name: "url", title: "Website", type: "url" }, { name: "logo", title: "Logo", type: "image" }] }],
    },
  ],
};
